import { StyleSheet } from 'react-native'
import {
  palette as kitPalette,
  spacing as kitSpacing,
  radii as kitRadii,
  shadows as kitShadows,
} from '../../ui'

/** Görev detay / tamamlama — ana sayfa kit dili. */
export const taskDetailStyles = StyleSheet.create({
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: kitSpacing.xl },
  empty: { color: kitPalette.slate[500], marginBottom: kitSpacing.lg, fontSize: 15 },
  backBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: kitSpacing.lg,
    paddingVertical: kitSpacing.sm,
  },
  backBtnText: {
    fontSize: 14,
    color: kitPalette.primary[700],
    fontWeight: '600',
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  lockTitle: {
    color: kitPalette.danger[700],
    fontWeight: '800',
    fontSize: 17,
    marginBottom: kitSpacing.sm,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  lockText: {
    color: kitPalette.slate[600],
    fontSize: 14,
    textAlign: 'center',
    paddingHorizontal: kitSpacing.xl,
    marginBottom: kitSpacing.lg,
    lineHeight: 21,
  },
  section: {
    backgroundColor: kitPalette.surface,
    borderRadius: kitRadii['2xl'],
    borderWidth: 1,
    borderColor: kitPalette.slate[200],
    padding: kitSpacing.lg,
    marginBottom: kitSpacing.md,
    ...kitShadows.sm,
  },
  sectionFlush: {
    padding: 0,
    overflow: 'hidden',
  },
  label: {
    fontSize: 11,
    color: kitPalette.slate[500],
    marginTop: kitSpacing.sm,
    marginBottom: 4,
    fontWeight: '700',
    fontFamily: 'PlusJakartaSans-Bold',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  value: {
    fontSize: 14,
    color: kitPalette.slate[800],
    fontFamily: 'PlusJakartaSans-Medium',
    lineHeight: 21,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: kitPalette.slate[800],
    marginBottom: kitSpacing.sm,
    fontFamily: 'PlusJakartaSans-Bold',
    letterSpacing: -0.2,
  },
  hint: {
    fontSize: 13,
    color: kitPalette.slate[500],
    marginBottom: kitSpacing.sm,
    lineHeight: 19,
  },
  noteInput: {
    borderWidth: 1,
    borderColor: kitPalette.slate[200],
    backgroundColor: kitPalette.slate[50],
    borderRadius: kitRadii.lg,
    paddingHorizontal: kitSpacing.md,
    paddingVertical: kitSpacing.md,
    fontSize: 14,
    color: kitPalette.slate[800],
    minHeight: 96,
    textAlignVertical: 'top',
    fontFamily: 'PlusJakartaSans-Medium',
  },
  noteSurface: {
    backgroundColor: kitPalette.surface,
    borderRadius: kitRadii['2xl'],
    borderWidth: 1,
    borderColor: kitPalette.slate[200],
    padding: kitSpacing.lg,
    marginBottom: kitSpacing.md,
    ...kitShadows.sm,
  },
  noteSurfaceMuted: {
    backgroundColor: kitPalette.primary[50],
    borderRadius: kitRadii['2xl'],
    borderWidth: 1,
    borderColor: kitPalette.primary[100],
    borderLeftWidth: 4,
    borderLeftColor: kitPalette.primary[600],
    padding: kitSpacing.lg,
    marginBottom: kitSpacing.md,
    ...kitShadows.sm,
  },
  noteBody: { fontSize: 14, color: kitPalette.slate[800], lineHeight: 22 },
  noteAfterTitle: { marginTop: kitSpacing.md },
  focusCard: {
    borderRadius: kitRadii['2xl'],
    borderWidth: 1,
    padding: kitSpacing.lg,
    marginBottom: kitSpacing.md,
    ...kitShadows.sm,
  },
  focusIconWrap: {
    width: 40,
    height: 40,
    borderRadius: kitRadii.lg,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: kitSpacing.sm,
  },
  focusTitle: {
    fontSize: 15,
    fontWeight: '800',
    fontFamily: 'PlusJakartaSans-Bold',
    marginBottom: 4,
  },
  focusHint: {
    fontSize: 13,
    lineHeight: 20,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  poolBanner: {
    backgroundColor: kitPalette.warning[50],
    borderRadius: kitRadii['2xl'],
    borderWidth: 1,
    borderColor: kitPalette.warning[200],
    borderLeftWidth: 4,
    borderLeftColor: kitPalette.warning[500],
    padding: kitSpacing.lg,
    marginBottom: kitSpacing.md,
    ...kitShadows.sm,
  },
  poolBadge: {
    paddingHorizontal: kitSpacing.sm,
    paddingVertical: 4,
    borderRadius: kitRadii.pill,
    backgroundColor: kitPalette.warning[100],
  },
  poolBadgeText: { color: kitPalette.warning[800], fontSize: 12, fontWeight: '800' },
  poolChipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: kitSpacing.xs, marginTop: kitSpacing.sm },
  poolChip: {
    paddingHorizontal: kitSpacing.sm,
    paddingVertical: 5,
    borderRadius: kitRadii.pill,
    backgroundColor: kitPalette.surface,
    borderWidth: 1,
    borderColor: kitPalette.warning[200],
  },
  poolChipDone: {
    backgroundColor: kitPalette.success[50],
    borderColor: kitPalette.success[200],
  },
  poolChipText: { fontSize: 12, fontWeight: '600', color: kitPalette.slate[700] },
  poolChipTextDone: { color: kitPalette.success[800], fontWeight: '700' },
  approvalBanner: {
    flexDirection: 'row',
    gap: kitSpacing.md,
    backgroundColor: kitPalette.success[50],
    borderRadius: kitRadii['2xl'],
    borderWidth: 1,
    borderColor: kitPalette.success[200],
    padding: kitSpacing.lg,
    marginBottom: kitSpacing.md,
    ...kitShadows.sm,
  },
  approvalIcon: {
    width: 40,
    height: 40,
    borderRadius: kitRadii.lg,
    backgroundColor: kitPalette.success[100],
    alignItems: 'center',
    justifyContent: 'center',
  },
  approvalTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: kitPalette.success[900],
    fontFamily: 'PlusJakartaSans-Bold',
  },
  approvalStep: { fontSize: 13, color: kitPalette.success[800], marginTop: 2 },
  approvalMetaRow: { flexDirection: 'row', flexWrap: 'wrap', gap: kitSpacing.md, marginTop: kitSpacing.sm },
  approvalMetaLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: kitPalette.success[700],
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  approvalMetaValue: { fontSize: 13, fontWeight: '600', color: kitPalette.success[900] },
  siraliBanner: {
    borderRadius: kitRadii['2xl'],
    borderWidth: 1,
    padding: kitSpacing.lg,
    marginBottom: kitSpacing.md,
    gap: kitSpacing.sm,
    ...kitShadows.sm,
  },
  siraliBannerWorker: { borderColor: kitPalette.primary[200], backgroundColor: kitPalette.primary[50] },
  siraliBannerAuditor: { borderColor: kitPalette.warning[200], backgroundColor: kitPalette.warning[50] },
  siraliBannerRejected: { borderColor: kitPalette.danger[200], backgroundColor: kitPalette.danger[50] },
  siraliBannerDone: { borderColor: kitPalette.success[200], backgroundColor: kitPalette.success[50] },
  siraliBannerWaiting: { borderColor: kitPalette.slate[200], backgroundColor: kitPalette.slate[50] },
  stepCard: {
    borderRadius: kitRadii.xl,
    borderWidth: 1,
    borderColor: kitPalette.slate[200],
    backgroundColor: kitPalette.slate[50],
    padding: kitSpacing.md,
    marginBottom: kitSpacing.sm,
  },
  stepCardCurrent: {
    borderColor: kitPalette.primary[300],
    backgroundColor: kitPalette.primary[50],
  },
  stepHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: kitSpacing.xs },
  stepIndex: { fontSize: 12, fontWeight: '800', color: kitPalette.slate[600], letterSpacing: 0.4 },
  stepTitle: { fontSize: 15, fontWeight: '700', color: kitPalette.slate[900], marginBottom: kitSpacing.xs },
  stepPill: {
    paddingHorizontal: kitSpacing.sm,
    paddingVertical: 4,
    borderRadius: kitRadii.pill,
    borderWidth: 1,
  },
  stepPillSuccess: { backgroundColor: kitPalette.success[50], borderColor: kitPalette.success[200] },
  stepPillError: { backgroundColor: kitPalette.danger[50], borderColor: kitPalette.danger[200] },
  stepPillPending: { backgroundColor: kitPalette.warning[50], borderColor: kitPalette.warning[200] },
  stepPillActive: { backgroundColor: kitPalette.primary[50], borderColor: kitPalette.primary[200] },
  stepPillNeutral: { backgroundColor: kitPalette.slate[100], borderColor: kitPalette.slate[200] },
  stepPillText: { fontSize: 11, fontWeight: '800' },
  stepPillTextSuccess: { color: kitPalette.success[800] },
  stepPillTextError: { color: kitPalette.danger[700] },
  stepPillTextPending: { color: kitPalette.warning[800] },
  stepPillTextActive: { color: kitPalette.primary[800] },
  stepPillTextNeutral: { color: kitPalette.slate[600] },
  stepMetaGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: kitSpacing.md, marginVertical: kitSpacing.xs },
  stepMetaLabel: { fontSize: 10, fontWeight: '700', color: kitPalette.slate[500], textTransform: 'uppercase' },
  stepMetaValue: { fontSize: 13, fontWeight: '600', color: kitPalette.slate[800] },
  stepDivider: { height: StyleSheet.hairlineWidth, backgroundColor: kitPalette.slate[200], marginVertical: kitSpacing.sm },
  stepPhotoGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: kitSpacing.sm },
  stepPhotoThumb: {
    width: 72,
    height: 72,
    borderRadius: kitRadii.lg,
    overflow: 'hidden',
    backgroundColor: kitPalette.slate[200],
  },
  photoThumb: {
    width: 88,
    height: 88,
    borderRadius: kitRadii.lg,
    overflow: 'hidden',
    backgroundColor: kitPalette.slate[200],
  },
  thumbImg: { width: '100%', height: '100%' },
  thumbTouchable: { flex: 1 },
  removeThumb: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: 'rgba(15,23,42,0.72)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  removeThumbText: { color: '#fff', fontSize: 14, fontWeight: '700', lineHeight: 16 },
  photoList: { flexDirection: 'row', flexWrap: 'wrap', gap: kitSpacing.sm },
  captureRow: { flexDirection: 'row', gap: kitSpacing.sm, marginBottom: kitSpacing.sm },
  captureBtn: {
    flex: 1,
    paddingVertical: kitSpacing.md,
    borderRadius: kitRadii.lg,
    backgroundColor: kitPalette.primary[50],
    borderWidth: 1,
    borderColor: kitPalette.primary[200],
    alignItems: 'center',
  },
  captureBtnSingle: { marginBottom: kitSpacing.sm },
  captureBtnText: { fontSize: 14, fontWeight: '700', color: kitPalette.primary[800] },
  videoDraftList: { gap: kitSpacing.sm, marginTop: kitSpacing.sm },
  videoDraftWrap: { position: 'relative', borderRadius: kitRadii.lg, overflow: 'hidden' },
  videoDraftPlayer: { width: '100%', height: 180, backgroundColor: kitPalette.slate[900] },
  videoEvidencePlayer: { width: '100%', height: 200, borderRadius: kitRadii.lg, backgroundColor: kitPalette.slate[900] },
  videoExpandBtn: {
    position: 'absolute',
    bottom: 8,
    right: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: kitRadii.pill,
    backgroundColor: 'rgba(15,23,42,0.65)',
  },
  videoExpandBtnText: { color: '#fff', fontSize: 11, fontWeight: '700' },
  documentRow: {
    paddingVertical: kitSpacing.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: kitPalette.slate[200],
  },
  documentRowText: { color: kitPalette.primary[700], fontWeight: '600', fontSize: 14 },
  documentDraftList: { gap: kitSpacing.xs, marginTop: kitSpacing.sm },
  documentDraftRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: kitSpacing.sm,
    borderRadius: kitRadii.lg,
    backgroundColor: kitPalette.slate[50],
    borderWidth: 1,
    borderColor: kitPalette.slate[200],
  },
  documentDraftName: { flex: 1, fontSize: 13, color: kitPalette.slate[800], marginRight: kitSpacing.sm },
  referencePhotoBadge: {
    position: 'absolute',
    bottom: 4,
    left: 4,
    right: 4,
    fontSize: 9,
    fontWeight: '700',
    color: '#fff',
    textAlign: 'center',
    backgroundColor: 'rgba(15,23,42,0.55)',
    borderRadius: 4,
    paddingVertical: 2,
  },
  checklistDraftRow: {
    paddingVertical: kitSpacing.xs,
    marginBottom: kitSpacing.sm,
  },
  draftText: { fontSize: 12, color: kitPalette.slate[500], fontWeight: '600' },
  questionList: { gap: kitSpacing.xs },
  questionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: kitSpacing.sm,
    padding: kitSpacing.sm,
    borderRadius: kitRadii.lg,
    borderWidth: 1,
    borderColor: kitPalette.slate[200],
    backgroundColor: kitPalette.slate[50],
  },
  questionItemActive: {
    borderWidth: 2,
    backgroundColor: kitPalette.surface,
    ...kitShadows.sm,
  },
  questionIndex: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: kitPalette.slate[200],
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 12,
    fontWeight: '800',
    color: kitPalette.slate[700],
    textAlign: 'center',
    lineHeight: 28,
  },
  questionTitle: { fontSize: 14, fontWeight: '700', color: kitPalette.slate[900] },
  questionMeta: { fontSize: 10, fontWeight: '700', color: kitPalette.slate[500], marginTop: 2 },
  questionCard: {
    marginTop: kitSpacing.sm,
    marginBottom: kitSpacing.md,
    padding: kitSpacing.md,
    borderRadius: kitRadii.lg,
    backgroundColor: kitPalette.surface,
    borderWidth: 1,
    borderColor: kitPalette.slate[200],
  },
  yesNoRow: { flexDirection: 'row', gap: kitSpacing.sm, marginBottom: kitSpacing.sm },
  answerBtn: {
    flex: 1,
    borderWidth: 1,
    borderColor: kitPalette.slate[200],
    backgroundColor: kitPalette.slate[50],
    borderRadius: kitRadii.lg,
    paddingVertical: kitSpacing.md,
    alignItems: 'center',
  },
  answerBtnActive: {
    backgroundColor: kitPalette.primary[50],
    borderColor: kitPalette.primary[400],
  },
  answerBtnText: { fontWeight: '800', color: kitPalette.slate[800], fontSize: 14 },
  itemLockedBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: kitSpacing.sm,
    padding: kitSpacing.sm,
    borderRadius: kitRadii.lg,
    backgroundColor: kitPalette.success[50],
    borderWidth: 1,
    borderColor: kitPalette.success[200],
    marginBottom: kitSpacing.sm,
  },
  itemLockedText: { flex: 1, fontSize: 13, color: kitPalette.success[800], fontWeight: '600' },
  itemRejectBanner: {
    flexDirection: 'row',
    gap: kitSpacing.sm,
    padding: kitSpacing.sm,
    borderRadius: kitRadii.lg,
    backgroundColor: kitPalette.danger[50],
    borderWidth: 1,
    borderColor: kitPalette.danger[200],
    marginBottom: kitSpacing.sm,
  },
  itemRejectTitle: { fontSize: 13, fontWeight: '800', color: kitPalette.danger[800] },
  itemRejectNote: { fontSize: 12, color: kitPalette.danger[700], marginTop: 2 },
  completionPanel: {
    backgroundColor: kitPalette.surface,
    borderRadius: kitRadii['2xl'],
    borderWidth: 1,
    borderColor: kitPalette.slate[200],
    padding: kitSpacing.lg,
    marginBottom: kitSpacing.md,
    ...kitShadows.sm,
  },
  workStatusWrap: {
    marginBottom: kitSpacing.md,
  },
})

export function accentBorderStyle(accent) {
  return { borderLeftWidth: 4, borderLeftColor: accent || kitPalette.primary[600] }
}
