-- ============================================================================
-- Şirket içi chat: birebir + grup, mesajlar, okundu (son okunan mesaj),
-- push kuyruğu (Edge Function / webhook ile Expo Push’a bağlanır).
--
-- Çevrimiçi: personeller.mobil_online / mobil_last_seen_at zaten var;
--   mobil AuthContext heartbeat ile güncelleniyorsa liste/konuşma başlığında
--   Realtime ile gösterilebilir (WhatsApp tarzı “son görülme”).
--
-- Push entegrasyonu: sohbet_push_kuyrugu satırlarını periyodik veya
--   Supabase Database Webhook (INSERT) ile Edge Function’dan
--   https://exp.host/--/api/v2/push/send işleyin; alıcı token personeller’den.
-- ============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- Tablolar
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.sohbet_kanallari (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ana_sirket_id uuid NOT NULL REFERENCES public.ana_sirketler (id) ON DELETE CASCADE,
  tur text NOT NULL CHECK (tur IN ('birebir', 'grup')),
  baslik text NULL,
  dm_user_low uuid NULL REFERENCES public.kullanicilar (id) ON DELETE CASCADE,
  dm_user_high uuid NULL REFERENCES public.kullanicilar (id) ON DELETE CASCADE,
  olusturan_kullanici_id uuid NOT NULL REFERENCES public.kullanicilar (id) ON DELETE CASCADE,
  olusturuldu_at timestamptz NOT NULL DEFAULT now(),
  son_mesaj_at timestamptz NULL,
  son_mesaj_ozet text NULL,
  CONSTRAINT sohbet_kanallari_dm_check CHECK (
    (
      tur = 'birebir'
      AND dm_user_low IS NOT NULL
      AND dm_user_high IS NOT NULL
      AND dm_user_low < dm_user_high
      AND baslik IS NULL
    )
    OR (
      tur = 'grup'
      AND dm_user_low IS NULL
      AND dm_user_high IS NULL
      AND baslik IS NOT NULL
      AND length(trim(baslik)) > 0
    )
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_sohbet_kanallari_dm_pair
  ON public.sohbet_kanallari (ana_sirket_id, dm_user_low, dm_user_high)
  WHERE tur = 'birebir';

CREATE INDEX IF NOT EXISTS idx_sohbet_kanallari_sirket_son_mesaj
  ON public.sohbet_kanallari (ana_sirket_id, son_mesaj_at DESC NULLS LAST);

CREATE TABLE IF NOT EXISTS public.sohbet_uyeleri (
  kanal_id uuid NOT NULL REFERENCES public.sohbet_kanallari (id) ON DELETE CASCADE,
  kullanici_id uuid NOT NULL REFERENCES public.kullanicilar (id) ON DELETE CASCADE,
  katilma_at timestamptz NOT NULL DEFAULT now(),
  son_okunan_mesaj_id bigint NULL,
  son_okuma_at timestamptz NULL,
  PRIMARY KEY (kanal_id, kullanici_id)
);

CREATE INDEX IF NOT EXISTS idx_sohbet_uyeleri_kullanici
  ON public.sohbet_uyeleri (kullanici_id);

CREATE TABLE IF NOT EXISTS public.sohbet_mesajlari (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kanal_id uuid NOT NULL REFERENCES public.sohbet_kanallari (id) ON DELETE CASCADE,
  gonderen_kullanici_id uuid NOT NULL REFERENCES public.kullanicilar (id) ON DELETE CASCADE,
  icerik text NOT NULL CHECK (char_length(icerik) <= 8000),
  olusturulma_at timestamptz NOT NULL DEFAULT now(),
  yanitlanan_mesaj_id bigint NULL REFERENCES public.sohbet_mesajlari (id) ON DELETE SET NULL,
  silindi_at timestamptz NULL
);

CREATE INDEX IF NOT EXISTS idx_sohbet_mesajlari_kanal_id
  ON public.sohbet_mesajlari (kanal_id, id DESC);

CREATE INDEX IF NOT EXISTS idx_sohbet_mesajlari_kanal_zaman
  ON public.sohbet_mesajlari (kanal_id, olusturulma_at DESC);

ALTER TABLE public.sohbet_uyeleri
  DROP CONSTRAINT IF EXISTS sohbet_uyeleri_son_okunan_fk;

ALTER TABLE public.sohbet_uyeleri
  ADD CONSTRAINT sohbet_uyeleri_son_okunan_fk
  FOREIGN KEY (son_okunan_mesaj_id) REFERENCES public.sohbet_mesajlari (id) ON DELETE SET NULL;

-- Push işlemesi dış sistemde (Edge Function); kuyruk RLS’siz service_role veya definer ile okunabilir
CREATE TABLE IF NOT EXISTS public.sohbet_push_kuyrugu (
  id bigserial PRIMARY KEY,
  mesaj_id bigint NOT NULL REFERENCES public.sohbet_mesajlari (id) ON DELETE CASCADE,
  kanal_id uuid NOT NULL REFERENCES public.sohbet_kanallari (id) ON DELETE CASCADE,
  alici_kullanici_id uuid NOT NULL REFERENCES public.kullanicilar (id) ON DELETE CASCADE,
  olusturuldu_at timestamptz NOT NULL DEFAULT now(),
  islendi_at timestamptz NULL
);

CREATE INDEX IF NOT EXISTS idx_sohbet_push_kuyrugu_bekleyen
  ON public.sohbet_push_kuyrugu (islendi_at, id)
  WHERE islendi_at IS NULL;

-- Kanal özeti güncelle + push kuyruğuna ekle (alıcılar = üyeler − gönderen)
CREATE OR REPLACE FUNCTION public.sohbet_mesaj_sonrasi()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  ozet text;
BEGIN
  ozet := LEFT(NEW.icerik, 180);
  UPDATE public.sohbet_kanallari
  SET
    son_mesaj_at = NEW.olusturulma_at,
    son_mesaj_ozet = ozet
  WHERE id = NEW.kanal_id;

  INSERT INTO public.sohbet_push_kuyrugu (mesaj_id, kanal_id, alici_kullanici_id)
  SELECT NEW.id, NEW.kanal_id, u.kullanici_id
  FROM public.sohbet_uyeleri u
  WHERE u.kanal_id = NEW.kanal_id
    AND u.kullanici_id <> NEW.gonderen_kullanici_id;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tr_sohbet_mesajlari_after_insert ON public.sohbet_mesajlari;
CREATE TRIGGER tr_sohbet_mesajlari_after_insert
  AFTER INSERT ON public.sohbet_mesajlari
  FOR EACH ROW
  EXECUTE FUNCTION public.sohbet_mesaj_sonrasi();

-- ---------------------------------------------------------------------------
-- RPC: birebir kanal (aynı şirket, iki kullanıcı)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.chat_baslat_birebir(p_alici_kullanici_id uuid)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_company uuid;
  v_me uuid := auth.uid();
  v_low uuid;
  v_high uuid;
  v_chan uuid;
BEGIN
  IF v_me IS NULL THEN
    RAISE EXCEPTION 'Oturum gerekli';
  END IF;
  IF p_alici_kullanici_id IS NULL OR p_alici_kullanici_id = v_me THEN
    RAISE EXCEPTION 'Geçersiz alıcı';
  END IF;

  SELECT p.ana_sirket_id INTO v_company
  FROM public.personeller p
  WHERE p.kullanici_id = v_me
    AND p.silindi_at IS NULL
  LIMIT 1;

  IF v_company IS NULL THEN
    RAISE EXCEPTION 'Personel kaydı bulunamadı';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.personeller p2
    WHERE p2.kullanici_id = p_alici_kullanici_id
      AND p2.ana_sirket_id = v_company
      AND p2.silindi_at IS NULL
  ) THEN
    RAISE EXCEPTION 'Alıcı aynı şirkette bulunamadı';
  END IF;

  v_low := LEAST(v_me, p_alici_kullanici_id);
  v_high := GREATEST(v_me, p_alici_kullanici_id);

  SELECT k.id INTO v_chan
  FROM public.sohbet_kanallari k
  WHERE k.ana_sirket_id = v_company
    AND k.tur = 'birebir'
    AND k.dm_user_low = v_low
    AND k.dm_user_high = v_high
  LIMIT 1;

  IF v_chan IS NOT NULL THEN
    RETURN v_chan;
  END IF;

  INSERT INTO public.sohbet_kanallari (
    ana_sirket_id,
    tur,
    dm_user_low,
    dm_user_high,
    olusturan_kullanici_id
  )
  VALUES (v_company, 'birebir', v_low, v_high, v_me)
  RETURNING id INTO v_chan;

  INSERT INTO public.sohbet_uyeleri (kanal_id, kullanici_id)
  VALUES (v_chan, v_me), (v_chan, p_alici_kullanici_id)
  ON CONFLICT (kanal_id, kullanici_id) DO NOTHING;

  RETURN v_chan;
END;
$$;

-- ---------------------------------------------------------------------------
-- RPC: grup kanalı (oluşturan + aynı şirkette üyeler)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.chat_grup_olustur(p_baslik text, p_uye_kullanici_idleri uuid[])
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_company uuid;
  v_me uuid := auth.uid();
  v_chan uuid;
  v_baslik text := trim(p_baslik);
  v_unique uuid[];
  u uuid;
BEGIN
  IF v_me IS NULL THEN
    RAISE EXCEPTION 'Oturum gerekli';
  END IF;
  IF v_baslik IS NULL OR length(v_baslik) = 0 THEN
    RAISE EXCEPTION 'Grup başlığı gerekli';
  END IF;

  SELECT p.ana_sirket_id INTO v_company
  FROM public.personeller p
  WHERE p.kullanici_id = v_me
    AND p.silindi_at IS NULL
  LIMIT 1;

  IF v_company IS NULL THEN
    RAISE EXCEPTION 'Personel kaydı bulunamadı';
  END IF;

  SELECT coalesce(array_agg(y ORDER BY y), ARRAY[]::uuid[])
  INTO v_unique
  FROM (
    SELECT DISTINCT x AS y
    FROM unnest(COALESCE(p_uye_kullanici_idleri, ARRAY[]::uuid[]) || ARRAY[v_me]::uuid[]) AS x
  ) sub;

  IF cardinality(v_unique) < 2 THEN
    RAISE EXCEPTION 'Grupta en az iki kişi olmalı';
  END IF;

  FOREACH u IN ARRAY v_unique LOOP
    IF NOT EXISTS (
      SELECT 1
      FROM public.personeller px
      WHERE px.kullanici_id = u
        AND px.ana_sirket_id = v_company
        AND px.silindi_at IS NULL
    ) THEN
      RAISE EXCEPTION 'Üye aynı şirkette değil: %', u;
    END IF;
  END LOOP;

  INSERT INTO public.sohbet_kanallari (
    ana_sirket_id,
    tur,
    baslik,
    olusturan_kullanici_id
  )
  VALUES (v_company, 'grup', v_baslik, v_me)
  RETURNING id INTO v_chan;

  INSERT INTO public.sohbet_uyeleri (kanal_id, kullanici_id)
  SELECT v_chan, x FROM unnest(v_unique) AS x
  ON CONFLICT (kanal_id, kullanici_id) DO NOTHING;

  RETURN v_chan;
END;
$$;

-- ---------------------------------------------------------------------------
-- RPC: mesaj gönder (üyelik doğrulaması)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.chat_mesaj_gonder(p_kanal_id uuid, p_icerik text)
RETURNS bigint
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  v_me uuid := auth.uid();
  v_mid bigint;
  v_text text := trim(p_icerik);
BEGIN
  IF v_me IS NULL THEN
    RAISE EXCEPTION 'Oturum gerekli';
  END IF;
  IF v_text IS NULL OR length(v_text) = 0 THEN
    RAISE EXCEPTION 'Mesaj boş olamaz';
  END IF;
  IF length(v_text) > 8000 THEN
    RAISE EXCEPTION 'Mesaj çok uzun';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.sohbet_uyeleri u
    JOIN public.personeller p ON p.kullanici_id = v_me AND p.silindi_at IS NULL
    JOIN public.sohbet_kanallari k ON k.id = u.kanal_id AND k.ana_sirket_id = p.ana_sirket_id
    WHERE u.kanal_id = p_kanal_id
      AND u.kullanici_id = v_me
  ) THEN
    RAISE EXCEPTION 'Bu kanala yazma yetkiniz yok';
  END IF;

  INSERT INTO public.sohbet_mesajlari (kanal_id, gonderen_kullanici_id, icerik)
  VALUES (p_kanal_id, v_me, v_text)
  RETURNING id INTO v_mid;

  RETURN v_mid;
END;
$$;

-- ---------------------------------------------------------------------------
-- RPC: okundu (WhatsApp tek tik / mavi tik için son okunan mesaj kimliği)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.chat_okundu_isaretle(p_kanal_id uuid, p_mesaj_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_me uuid := auth.uid();
BEGIN
  IF v_me IS NULL THEN
    RAISE EXCEPTION 'Oturum gerekli';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.sohbet_mesajlari m
    JOIN public.sohbet_uyeleri u ON u.kanal_id = m.kanal_id AND u.kullanici_id = v_me
    WHERE m.kanal_id = p_kanal_id
      AND m.id = p_mesaj_id
      AND m.silindi_at IS NULL
  ) THEN
    RAISE EXCEPTION 'Mesaj veya kanal geçersiz';
  END IF;

  UPDATE public.sohbet_uyeleri u
  SET
    son_okunan_mesaj_id = GREATEST(COALESCE(u.son_okunan_mesaj_id, 0), p_mesaj_id),
    son_okuma_at = now()
  WHERE u.kanal_id = p_kanal_id
    AND u.kullanici_id = v_me;
END;
$$;

-- Oturum kullanıcısının kanal üyesi olup olmadığı. RLS politikasında doğrudan
-- sohbet_uyeleri alt sorgusu kullanılırsa aynı SELECT politikası tekrar tetiklenir
-- (sonsuz özyineleme). Kontrol burada DEFINER + tablo sahibi bağlamında yapılır.
CREATE OR REPLACE FUNCTION public.chat_kanal_uyesi_mi(p_kanal_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.sohbet_uyeleri u
    WHERE u.kanal_id = p_kanal_id
      AND u.kullanici_id = auth.uid()
  );
$$;

REVOKE ALL ON FUNCTION public.chat_kanal_uyesi_mi(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.chat_kanal_uyesi_mi(uuid) TO authenticated;

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------

ALTER TABLE public.sohbet_kanallari ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sohbet_uyeleri ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sohbet_mesajlari ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sohbet_push_kuyrugu ENABLE ROW LEVEL SECURITY;

-- Kanallar: şirketim + üyeliğim. sohbet_uyeleri alt sorgusu kullanılmaz — uyeleri_select
-- zaten kanalları okur; karşılıklı politikalar sonsuz özyinelemeye düşerdi.
CREATE POLICY sohbet_kanallari_select ON public.sohbet_kanallari
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.personeller p
      WHERE p.kullanici_id = auth.uid()
        AND p.silindi_at IS NULL
        AND sohbet_kanallari.ana_sirket_id = p.ana_sirket_id
    )
    AND public.chat_kanal_uyesi_mi(sohbet_kanallari.id)
  );

-- Üyeler
CREATE POLICY sohbet_uyeleri_select ON public.sohbet_uyeleri
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.personeller p
      JOIN public.sohbet_kanallari k
        ON k.id = sohbet_uyeleri.kanal_id
       AND k.ana_sirket_id = p.ana_sirket_id
      WHERE p.kullanici_id = auth.uid()
        AND p.silindi_at IS NULL
    )
    AND public.chat_kanal_uyesi_mi(sohbet_uyeleri.kanal_id)
  );

CREATE POLICY sohbet_uyeleri_update_own ON public.sohbet_uyeleri
  FOR UPDATE TO authenticated
  USING (kullanici_id = auth.uid())
  WITH CHECK (kullanici_id = auth.uid());

-- Mesajlar
CREATE POLICY sohbet_mesajlari_select ON public.sohbet_mesajlari
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.sohbet_uyeleri u
      JOIN public.personeller p ON p.kullanici_id = auth.uid() AND p.silindi_at IS NULL
      JOIN public.sohbet_kanallari k ON k.id = sohbet_mesajlari.kanal_id AND k.ana_sirket_id = p.ana_sirket_id
      WHERE u.kanal_id = sohbet_mesajlari.kanal_id
        AND u.kullanici_id = auth.uid()
    )
    AND silindi_at IS NULL
  );

CREATE POLICY sohbet_mesajlari_insert ON public.sohbet_mesajlari
  FOR INSERT TO authenticated
  WITH CHECK (
    gonderen_kullanici_id = auth.uid()
    AND EXISTS (
      SELECT 1
      FROM public.sohbet_uyeleri u
      JOIN public.personeller p ON p.kullanici_id = auth.uid() AND p.silindi_at IS NULL
      JOIN public.sohbet_kanallari k ON k.id = sohbet_mesajlari.kanal_id AND k.ana_sirket_id = p.ana_sirket_id
      WHERE u.kanal_id = sohbet_mesajlari.kanal_id
        AND u.kullanici_id = auth.uid()
    )
  );

-- Push kuyruğu: doğrudan istemci okuyamaz (işleyici service_role)
CREATE POLICY sohbet_push_kuyrugu_deny ON public.sohbet_push_kuyrugu
  FOR ALL TO authenticated
  USING (false)
  WITH CHECK (false);

GRANT SELECT, INSERT, UPDATE ON public.sohbet_kanallari TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.sohbet_uyeleri TO authenticated;
GRANT SELECT, INSERT ON public.sohbet_mesajlari TO authenticated;
-- push kuyruğu yok

GRANT EXECUTE ON FUNCTION public.chat_baslat_birebir(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.chat_grup_olustur(text, uuid[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.chat_mesaj_gonder(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.chat_okundu_isaretle(uuid, bigint) TO authenticated;

-- ---------------------------------------------------------------------------
-- Realtime (mesaj + üye okuma + kanal özeti; çevrimiçi için personeller zaten ekli olabilir)
-- ---------------------------------------------------------------------------

DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.sohbet_kanallari;
  EXCEPTION WHEN duplicate_object THEN NULL;
  END;
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.sohbet_uyeleri;
  EXCEPTION WHEN duplicate_object THEN NULL;
  END;
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.sohbet_mesajlari;
  EXCEPTION WHEN duplicate_object THEN NULL;
  END;
END $$;

COMMENT ON TABLE public.sohbet_push_kuyrugu IS
  'Yeni mesajda tetiklenir; Edge Function veya cron service_role ile okuyup Expo Push gönderir; islendi_at güncellenir.';

COMMENT ON FUNCTION public.chat_okundu_isaretle(uuid, bigint) IS
  'Sohbet ekranında en alta kayınca son mesaj id ile çağırın; birebirde karşı taraf gonderdiği mesajlar için son_okunan >= mesaj id ise mavi tik mantığı kurulur.';

GRANT USAGE, SELECT ON SEQUENCE public.sohbet_mesajlari_id_seq TO authenticated;

COMMIT;
