export { default as TaskDetailShell } from './TaskDetailShell.jsx'
export { default as TaskDetailHeader } from './TaskDetailHeader.jsx'
export { default as TaskDetailBody } from './TaskDetailBody.jsx'
export { default as TaskDetailSidebar } from './TaskDetailSidebar.jsx'
export { default as TaskDetailActionBar, TaskDetailActionButton } from './TaskDetailActionBar.jsx'
export { default as TaskDetailEvidence } from './TaskDetailEvidence.jsx'
export { default as TaskDetailTimeline } from './TaskDetailTimeline.jsx'
export { default as TaskDetailSection } from './TaskDetailSection.jsx'
export { TaskDetailDeletionAlert } from './TaskDetailAlert.jsx'
export { getTaskDetailConfig } from './taskDetailConfig.js'
